### ISSUE TITLE
Why do you list pre-shared keys on this page?

### ISSUE THREAD

**Issue by baimafeima** [proxysh/start#1]
https://github.com/proxysh/start
See: https://i.imgur.com/36ZqleS.png

**Comment by proxysh** [comment]
These are public security keys that anyone needs to know to connect to our network in addition to confidential username/password auth pair. It is the same as the instructions we provide in your welcome email. There is little reason to hide them as they are handed out in a similar fashion to everyone who signs up at Proxy.sh. Furthermore, we do not recommend using anything else but our OpenVPN tunnels as far as security is involved. L2TP and PPTP are crackable, but we still offer them as free extras for clients who have no alternative in their devices' OS.
